name: Test
'on':
  push:
    types: []
jobs:
  Job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Get latest release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: akremi-khayreddine/dx-test
        env: {}
      - id: hi-webhhok
        name: Webhook
        uses: distinctlab/dx-actions-loader@master
        if: always()
        env:
          GITHUB_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        with:
          private_action: akremi-khayreddine/hi-pipelines-webhook-action@master
          project_id: test-pipeline
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          job_name: Job1
          job_status: '${{ job.status }}'
          next_job: Job3
          run_id: '${{ github.run_id }}'
  Job3:
    name: Job3
    runs-on: ubuntu-latest
    needs: Job1
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: '${{ github.repository }}'
          token: '${{ github.token }}'
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
        env: {}
      - id: set-up-node
        name: Setup node
        with:
          always-auth: 'false'
          node-version: 10.x
        env: {}
        uses: actions/setup-node@v1
      - id: build
        name: Build app
        with: {}
        env: {}
        run: npm run build-app
      - id: hi-webhhok
        name: Webhook
        uses: distinctlab/dx-actions-loader@master
        if: always()
        env:
          GITHUB_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        with:
          private_action: akremi-khayreddine/hi-pipelines-webhook-action@master
          project_id: test-pipeline
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          job_name: Job3
          job_status: '${{ job.status }}'
          run_id: '${{ github.run_id }}'
