name: Test
'on':
  pull_request:
    types:
      - opened
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: release
        name: Get latest release
        with:
          repository: akremi-khayreddine/dx-test
        env: {}
        uses: pozetroninc/github-action-get-latest-release@master
      - id: hi-webhhok
        name: Webhook
        uses: distinctlab/dx-actions-loader@master
        if: always()
        env:
          GITHUB_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        with:
          private_action: akremi-khayreddine/hi-pipelines-webhook-action@master
          project_id: test-pipeline
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          job_name: Test
          job_status: '${{ job.status }}'
          run_id: '${{ github.run_id }}'
          job_payload: '{"version":"${{ steps.release.outputs.release }}"}'
